FROM python

RUN pip install pandas
RUN pip install boto
RUN pip install beautifulsoup4
RUN pip install urllib3
Run pip install requests
Run pip install lxml
RUN pip install html5lib

COPY Problem_1.py /Problem_1.py
CMD [ "python", "./Problem_1.py","2012","51143","000005114313000007","42324","23894332","us-west-2"]